#if !canImport(ObjectiveC)
import XCTest

extension LexerTest {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LexerTest = [
        ("testReadChar", testReadChar),
        ("testReadline", testReadline),
    ]
}

extension StringExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringExtensionsTests = [
        ("testIntSubscripts", testIntSubscripts),
        ("testPerformanceExample", testPerformanceExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(LexerTest.__allTests__LexerTest),
        testCase(StringExtensionsTests.__allTests__StringExtensionsTests),
    ]
}
#endif
